CREATE TABLE people (
                        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(100) NOT NULL ,
                        year_of_birth INT NOT NULL,
                        username VARCHAR(100) NOT NULL,
                        password VARCHAR(100) NOT NULL,
                        role VARCHAR(100)
);


CREATE TABLE books (
                       id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       title varchar(100) NOT NULL,
                       author varchar(100) NOT NULL,
                       year INT NOT NULL,
                       take_time timestamp,
                       owner_id INT,
                       FOREIGN KEY (owner_id) REFERENCES people(id) ON DELETE SET NULL
)